# Generated by Django 2.1 on 2019-05-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bluetoothpassword',
            name='barcode',
            field=models.CharField(max_length=32, null=True, verbose_name='条码'),
        ),
    ]
