# Generated by Django 2.1 on 2019-06-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0002_bluetoothpassword_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bluetoothpassword',
            name='password',
            field=models.CharField(max_length=32, verbose_name='蓝牙密码'),
        ),
    ]
